# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.TextField(max_length=50)),
                ('region', models.TextField(blank=True, max_length=50, null=True)),
                ('department', models.TextField(blank=True, max_length=50, null=True)),
                ('county', models.TextField(blank=True, max_length=50, null=True)),
                ('city', models.TextField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
