# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_party_parent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Position',
            new_name='PoliticalFunction',
        ),
        migrations.RenameField(
            model_name='detailedresults',
            old_name='voteNumber',
            new_name='vote_number',
        ),
        migrations.RenameField(
            model_name='party',
            old_name='year_in_school',
            new_name='political_orientation',
        ),
        migrations.RenameField(
            model_name='poll',
            old_name='pollInstitute',
            new_name='poll_institute',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='votingResult',
            new_name='voting_result',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='positionType',
            new_name='position_type',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='birthDate',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='birthPlace',
        ),
        migrations.RemoveField(
            model_name='role',
            name='beginningDate',
        ),
        migrations.RemoveField(
            model_name='role',
            name='endDate',
        ),
        migrations.AddField(
            model_name='candidate',
            name='birth_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='birth_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Place'),
        ),
        migrations.AddField(
            model_name='role',
            name='beginning_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='election',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='creationDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
