# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 19:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20161212_1908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='party',
            old_name='creationDate',
            new_name='creation_date',
        ),
    ]
