# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-09 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20161214_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrendSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='poll',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='election',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='place',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='poll_institute',
        ),
        migrations.AddField(
            model_name='candidate',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_nationality', to='polls.Place'),
        ),
        migrations.AddField(
            model_name='role',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Candidate'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='birth_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_birth_place', to='polls.Place'),
        ),
        migrations.DeleteModel(
            name='Poll',
        ),
        migrations.DeleteModel(
            name='PollInstitute',
        ),
        migrations.AddField(
            model_name='trend',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Candidate'),
        ),
        migrations.AddField(
            model_name='trend',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Election'),
        ),
        migrations.AddField(
            model_name='trend',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Place'),
        ),
        migrations.AddField(
            model_name='trend',
            name='trend_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.TrendSource'),
        ),
    ]
