# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-16 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20170109_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politicalfunction',
            name='position',
            field=models.CharField(max_length=200),
        ),
    ]
