# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-05 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20170116_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='image_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
