# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-05 18:51
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_candidate_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='image_url',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
