# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-12 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20170210_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Party'),
        ),
    ]
