# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-08 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_statistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistics',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
