# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-12 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20170212_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trend',
            name='score',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='trend',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
